services:
  postgres:
    image: ${DOCKER_POSTGRES_IMAGE}
    container_name: ${DOCKER_POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DOCKER_POSTGRES_PORTS}
    volumes:
      - ${DOCKER_POSTGRES_VOLUMES}

  liquibase:
    image: ${DOCKER_LIQUIBASE_IMAGE}
    container_name: ${DOCKER_LIQUIBASE_CONTAINER_NAME}
    depends_on:
      - postgres
    working_dir: /liquibase
    volumes:
      - ./usr1/src/main/resources/db/changelog:/liquibase/changelog
    command: >
      update
      --url=jdbc:postgresql://postgres:5432/mydb
      --username=root
      --password=1111
      --changeLogFile=changelog/db.changelog-master.xml

  userservice:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1111
    ports:
      - "8083:8083"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data: